postgresql:
  initdbScripts:
    init.sql: |-
      CREATE USER fees_register WITH PASSWORD 'fees_register';
      CREATE DATABASE fees_register WITH OWNER = fees_register ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  persistence:
    enabled: false

java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  applicationPort: 8080
  memoryRequests: 256Mi
  cpuRequests: 0.2
  memoryLimits: 1024Mi
  cpuLimits: 1
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://${SERVICE_NAME}-postgresql:5432/fees_register
    SPRING_DATASOURCE_USERNAME: fees_register
    SPRING_DATASOURCE_PASSWORD: fees_register

    REFORM_SERVICE_NAME: fees-register-api
    REFORM_TEAM: cc
    REFORM_ENVIRONMENT: preview

    ENABLE_FEE_LOADER: true
    SPRING_LIQUIBASE_ENABLED: true
    IDAM_CLIENT_BASE_URL: https://preprod-idamapi.reform.hmcts.net:3511

    APPINSIGHTS_INSTRUMENTATIONKEY: fake-key
